# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Centered Cusum of Values
#'
#' @param y Vector of centered, cumulative sum of squares
#' @returns Vector of centered, cumulative sum of squares
CenteredCusumValues <- function(y) {
    .Call(`_RcppICSS_CenteredCusumValues`, y)
}

#' Check Critical Value
#'
#' @param Dk Vector of centered, cumulative sum of squares
#' @returns List with position and an indicator of significance
check_critical_value <- function(Dk) {
    .Call(`_RcppICSS_check_critical_value`, Dk)
}

#' Check Convergence
#'
#' @param oldVec Integer vector of old positions.
#' @param newVec Integer vector of new positions.
#' @returns Boolean that indicates if ICSS algorithm converged.
is_converged <- function(oldVec, newVec) {
    .Call(`_RcppICSS_is_converged`, oldVec, newVec)
}

ICSS_step_1_and_2 <- function(x) {
    .Call(`_RcppICSS_ICSS_step_1_and_2`, x)
}

