# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stat.resid <- function(x, a__ = NULL, order = 1L, factor = 8, epsilon = 0.0) {
    .Call(`_RcppBASTA_stat_resid`, x, a__, order, factor, epsilon)
}

bin.segm <- function(buh, th) {
    .Call(`_RcppBASTA_bin_segm`, buh, th)
}

inner.prod.iter <- function(x) {
    .Call(`_RcppBASTA_inner_prod_iter`, x)
}

med <- function(x) {
    .Call(`_RcppBASTA_med`, x)
}

